apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx-router
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-router
    spec:
      containers:
        - name: nginx-router-container
          image: nginx:latest
          ports:
            - containerPort: 80

