apiVersion: v1
kind: Pod
metadata:
  name: nginx-router
spec:
  containers:
  - name: nginx-router
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
    - name: nginx-config-volume
      mountPath: /etc/nginx/nginx.conf
      subPath: nginx.conf
  volumes:
  - name: nginx-config-volume
    configMap:
      name: nginx-config